---
micronaut:
    application:
        name: bug

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

---
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

